#!/bin/bash -e

REPORT=/tmp/report.txt

MONITOR=/scans/monitor.pcap

python network_tests.py connection.dhcp_long $MONITOR $TARGET_IP
python network_tests.py connection.min_send $MONITOR $TARGET_IP

cat report.txt >> $REPORT
