#!/bin/bash -e
source reporting_utils
REPORT=/tmp/report.txt
RESULT_LINES=""
MONOLITH_LOG=""
LOCAL_REPORT=tmp/report.txt
MANIFEST=./module_manifest.json

if [ -n "$TARGET_IP" ]; then
    echo Collecting TLS cert from target address $TARGET_IP.
    java -jar tlstest/build/libs/tlstest.jar $TARGET_IP
    RESULT_LINES=$(grep "RESULT" $LOCAL_REPORT)
    MONOLITH_LOG=$(grep -v "RESULT" $LOCAL_REPORT)


    write_out_result $REPORT \
                     "tls" \
                     "more descriptions to follow..." \
                     ""$MONOLITH_LOG \
                     "$RESULT_LINES"

else
    MONOLITH_LOG="TARGET_IP not configured TLS test failed"
    echo $MONOLITH_LOG

    write_out_result $REPORT \
                     "tls" \
                     "more descriptions to follow..." \
                     "$MONOLITH_LOG" \
                     "$(grep "RESULT" $LOCAL_REPORT)"

fi

result_lines=( "$RESULT_LINES" )

[ $(check_for_fails_in "${result_lines[@]}") == false ]
