#!/bin/bash -e

if [ -n "$TARGET_IP" ]; then
	echo Using the host address from $TARGET_IP and mac address $TARGET_MAC

	curl https://svn.nmap.org/nmap/nmap-mac-prefixes | tee security_passwords/src/main/resources/macList.txt
        java -jar security_passwords/build/libs/security_passwords-1.0-SNAPSHOT-all.jar $TARGET_IP telnet 23 $TARGET_MAC my-site.com
	cp -r ./reports/report.txt /tmp/report.txt
else
	echo Wrong parametres Password test failed | tee /tmp/report.txt
fi
