#!/bin/bash -e
source reporting_utils
REPORT=/tmp/report.txt
RESULT_LINES=""
LOCAL_REPORT=tmp/report.txt
MANIFEST=./module_manifest.json

if [ -n "$TARGET_IP" ]; then
    echo Collecting TLS cert from target address $TARGET_IP.
    java -jar tlstest/build/libs/tlstest.jar $TARGET_IP
    RESULT_LINES=$(grep "RESULT" $LOCAL_REPORT)

    write_out_result $REPORT \
                     "tls" \
                     "more descriptions to follow..." \
                     "$(grep -v "RESULT" $LOCAL_REPORT)" \
                     "$RESULT_LINES"

else
    echo TARGET_IP not configured TLS test failed

    write_out_result $REPORT \
                     "tls" \
                     "more descriptions to follow..." \
                     "TARGET_IP not configured TLS test failed" \
                     "$(grep "RESULT" $LOCAL_REPORT)"

fi

result_lines=( "$RESULT_LINES" )

[ $(check_for_fails_in "${result_lines[@]}") == false ]
