#!/bin/bash -e

if [ -n "$TARGET_IP" ]; then
	echo Using the host address from $TARGET_IP and mac address $TARGET_MAC

	curl https://svn.nmap.org/nmap/nmap-mac-prefixes | tee security_passwords/src/main/resources/macList.txt

	java -jar security_passwords/build/libs/security_passwords-1.0-SNAPSHOT-all.jar $TARGET_IP http 80 $TARGET_MAC nginx-site
	cat ./reports/http_report.txt >> ./reports/report.txt

	java -jar security_passwords/build/libs/security_passwords-1.0-SNAPSHOT-all.jar $TARGET_IP https 443 $TARGET_MAC nginx-site
	cat ./reports/https_report.txt >> ./reports/report.txt

	java -jar security_passwords/build/libs/security_passwords-1.0-SNAPSHOT-all.jar $TARGET_IP telnet 23 $TARGET_MAC nginx-site
	cat ./reports/telnet_report.txt >> ./reports/report.txt

	java -jar security_passwords/build/libs/security_passwords-1.0-SNAPSHOT-all.jar $TARGET_IP ssh 22 $TARGET_MAC nginx-site
	cat ./reports/ssh_report.txt >> ./reports/report.txt

	cp -r ./reports/report.txt /tmp/report.txt
else
	echo Wrong parametres Password test failed | tee /tmp/report.txt
fi
